type JsonLdProps = {
  /** One schema object, or several to emit inside a single @graph. */
  schema: Record<string, unknown> | Record<string, unknown>[];
};

/**
 * Emits structured data. Rendered from server components only, so the JSON
 * is in the initial HTML where crawlers will actually see it.
 */
export function JsonLd({ schema }: JsonLdProps) {
  const payload = Array.isArray(schema)
    ? { "@context": "https://schema.org", "@graph": schema }
    : { "@context": "https://schema.org", ...schema };

  return (
    <script
      type="application/ld+json"
      // Structured data is generated by us, never from user input.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(payload) }}
    />
  );
}
